<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\DocumentoEscaneado;

class DocumentoEscaneadoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $documentos = [
            [
                'archivo_original' => 'documentos_escaneados/ejemplo1.jpg',
                'nombre_archivo' => 'ejemplo1.jpg',
                'tipo_mime' => 'image/jpeg',
                'tamaño_archivo' => 245760,
                'folio' => 'TX-001234',
                'fecha_documento' => '2024-12-01',
                'remitente_nombre' => 'MARIA GONZALEZ',
                'remitente_telefono' => '713-555-0123',
                'remitente_direccion' => '1234 MAIN ST APT 2B',
                'remitente_colonia' => 'DOWNTOWN',
                'remitente_ciudad' => 'HOUSTON',
                'remitente_estado' => 'TX',
                'remitente_cp' => '77002',
                'remitente_pais' => 'US',
                'destinatario_nombre' => 'CARLOS MARTINEZ',
                'destinatario_telefono' => '55-1234-5678',
                'destinatario_direccion' => 'AV INSURGENTES 456 COL ROMA',
                'destinatario_colonia' => 'ROMA NORTE',
                'destinatario_ciudad' => 'CIUDAD DE MEXICO',
                'destinatario_estado' => 'CDMX',
                'destinatario_cp' => '06700',
                'destinatario_pais' => 'MX',
                'numero_cajas' => 2,
                'tipo_contenido' => 'ROPA USADA',
                'peso' => 25.5,
                'valor_asegurado' => 150.00,
                'valor_declarado' => 150.00,
                'costo_flete' => 45.00,
                'impuestos' => 8.50,
                'seguro_extra' => 3.00,
                'total' => 56.50,
                'estado_procesamiento' => 'procesado',
                'requiere_revision' => false,
                'texto_raw' => 'FOLIO: TX-001234\nFECHA: 01/12/2024\nREMITENTE: MARIA GONZALEZ...',
                'confianza_ocr' => '{"general": 95, "folio": 98, "nombres": 92, "direcciones": 94}',
                'metadatos_vision' => '{"processing_time": "2.3s", "confidence": 95}',
            ],
            [
                'archivo_original' => 'documentos_escaneados/ejemplo2.jpg',
                'nombre_archivo' => 'ejemplo2.jpg',
                'tipo_mime' => 'image/jpeg',
                'tamaño_archivo' => 198432,
                'folio' => 'CA-005678',
                'fecha_documento' => '2024-12-02',
                'remitente_nombre' => 'JOHN SMITH',
                'remitente_telefono' => '323-555-9876',
                'remitente_direccion' => '5678 SUNSET BLVD',
                'remitente_colonia' => 'HOLLYWOOD',
                'remitente_ciudad' => 'LOS ANGELES',
                'remitente_estado' => 'CA',
                'remitente_cp' => '90028',
                'remitente_pais' => 'US',
                'destinatario_nombre' => 'ANA RODRIGUEZ',
                'destinatario_telefono' => '33-9876-5432',
                'destinatario_direccion' => 'CALLE MORELOS 123',
                'destinatario_colonia' => 'CENTRO',
                'destinatario_ciudad' => 'GUADALAJARA',
                'destinatario_estado' => 'JALISCO',
                'destinatario_cp' => '44100',
                'destinatario_pais' => 'MX',
                'numero_cajas' => 1,
                'tipo_contenido' => 'ELECTRODOMESTICOS',
                'peso' => 15.0,
                'valor_asegurado' => 300.00,
                'valor_declarado' => 300.00,
                'costo_flete' => 65.00,
                'impuestos' => 12.75,
                'seguro_extra' => 6.00,
                'total' => 83.75,
                'estado_procesamiento' => 'procesado',
                'requiere_revision' => false,
                'texto_raw' => 'FOLIO: CA-005678\nFECHA: 02/12/2024\nREMITENTE: JOHN SMITH...',
                'confianza_ocr' => '{"general": 88, "folio": 95, "nombres": 85, "direcciones": 87}',
                'metadatos_vision' => '{"processing_time": "1.8s", "confidence": 88}',
            ],
            [
                'archivo_original' => 'documentos_escaneados/ejemplo3.jpg',
                'nombre_archivo' => 'ejemplo3.jpg',
                'tipo_mime' => 'image/jpeg',
                'tamaño_archivo' => 312089,
                'folio' => 'FL-003344',
                'fecha_documento' => '2024-12-03',
                'remitente_nombre' => 'LUIS FERNANDEZ',
                'remitente_telefono' => '786-555-4455',
                'remitente_direccion' => '8901 OCEAN DRIVE',
                'remitente_colonia' => 'SOUTH BEACH',
                'remitente_ciudad' => 'MIAMI',
                'remitente_estado' => 'FL',
                'remitente_cp' => '33139',
                'remitente_pais' => 'US',
                'destinatario_nombre' => 'SOFIA GUTIERREZ',
                'destinatario_telefono' => '81-7788-9900',
                'destinatario_direccion' => 'AV UNIVERSIDAD 789',
                'destinatario_colonia' => 'SAN NICOLAS',
                'destinatario_ciudad' => 'MONTERREY',
                'destinatario_estado' => 'NUEVO LEON',
                'destinatario_cp' => '66450',
                'destinatario_pais' => 'MX',
                'numero_cajas' => 3,
                'tipo_contenido' => 'JUGUETES',
                'peso' => 18.7,
                'valor_asegurado' => 85.00,
                'valor_declarado' => 85.00,
                'costo_flete' => 38.00,
                'impuestos' => 7.25,
                'seguro_extra' => 2.50,
                'total' => 47.75,
                'estado_procesamiento' => 'procesado',
                'requiere_revision' => true,
                'texto_raw' => 'FOLIO: FL-003344\nFECHA: 03/12/2024\nREMITENTE: LUIS FERNANDEZ...',
                'confianza_ocr' => '{"general": 75, "folio": 90, "nombres": 70, "direcciones": 72}',
                'metadatos_vision' => '{"processing_time": "3.1s", "confidence": 75}',
                'notas_revision' => 'Revisar dirección del destinatario, OCR con baja confianza',
            ],
            [
                'archivo_original' => 'documentos_escaneados/error_ejemplo.jpg',
                'nombre_archivo' => 'error_ejemplo.jpg',
                'tipo_mime' => 'image/jpeg',
                'tamaño_archivo' => 156789,
                'estado_procesamiento' => 'error',
                'requiere_revision' => true,
                'errores_procesamiento' => 'Error: Imagen muy borrosa, no se pudo extraer texto legible',
                'texto_raw' => '',
                'metadatos_vision' => '{"processing_time": "1.2s", "error": "Low quality image"}',
                'notas_revision' => 'Imagen de muy baja calidad, solicitar nueva foto al cliente',
            ]
        ];

        foreach ($documentos as $documento) {
            DocumentoEscaneado::create($documento);
        }
    }
}
